version: "3.7"

services:
    mysql:
        image: "mysql:8.0"
        container_name: 'back_mysql'
        environment:
            MYSQL_ROOT_PASSWORD: "${TYPEORM_PASSWORD}"
            MYSQL_DATABASE: "${TYPEORM_DATABASE}"
            MYSQL_USER: "${TYPEORM_USERNAME}"
            MYSQL_PASSWORD: "${TYPEORM_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        volumes:
            - "backmysql:/var/lib/mysql"
        networks:
            - backend
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]

    redis:
        image: "redis:alpine"
        container_name: 'back_redis'
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "backredis:/data"
        networks:
            - backend
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]

    mailhog:
        image: "mailhog/mailhog:latest"
        container_name: 'back_mailhog'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    backmysql:
        driver: local
    backredis:
        driver: local
